### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by rattrayalex** [jscott1989/python-pipedrive#3]
Hi, 

This repo hasn't been updated for 2 years. Do you have any idea how far it's likely to have fallen behind the production Pipedrive API?

**Comment by jscott1989** [comment]
Hi.

I haven't used Pipedrive since I left the company where I developed python-pipedrive. Sorry!

For the most part it's a very light wrapper on the API though so I can't imagine there'd be too many changes needed if any to make it work.

If you do try it out let me know if it works :) And if you make any changes send a pull request :+1:

**Comment by rattrayalex** [comment]
Cool, thanks!

**Comment by Miserlou** [comment]
@rattrayalex - did it work? :)

**Comment by rattrayalex** [comment]
I didn't try. If you do, comment here!

**Comment by Miserlou** [comment]
Works okay for me!
